#!/usr/bin/env node
// Build script: converts HYG v41 CSV → stars.js for the Fairy Calendar sky chart.
// Run: node build-stars.js
// Input: hygdata_v41.csv (in same directory)
// Output: stars.js

const fs = require('fs');

const csv = fs.readFileSync('hygdata_v41.csv', 'utf8');
const lines = csv.split('\n');
const header = lines[0].replace(/"/g, '').split(',');

const idx = {};
header.forEach((h, i) => idx[h] = i);

// Parse CSV row (handles quoted fields)
function parseRow(line) {
  const fields = [];
  let cur = '', inQuote = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') { inQuote = !inQuote; continue; }
    if (ch === ',' && !inQuote) { fields.push(cur); cur = ''; continue; }
    cur += ch;
  }
  fields.push(cur);
  return fields;
}

// HYG constellation abbreviations → our display names
const CON_MAP = {
  'UMi': 'Ursa Minor', 'Cas': 'Cassiopeia', 'Cep': 'Cepheus', 'Dra': 'Draco',
  'UMa': 'Ursa Major', 'Boo': 'Boötes', 'CrB': 'Corona Bor.',
  'And': 'Andromeda', 'Psc': 'Pisces', 'Ari': 'Aries', 'Per': 'Perseus',
  'Tau': 'Taurus', 'Ori': 'Orion', 'CMa': 'Canis Major', 'CMi': 'Canis Minor',
  'Aur': 'Auriga', 'Gem': 'Gemini', 'Cnc': 'Cancer', 'Leo': 'Leo',
  'Vir': 'Virgo', 'Lib': 'Libra', 'Sco': 'Scorpius', 'Her': 'Hercules',
  'Oph': 'Ophiuchus', 'Lyr': 'Lyra', 'Sgr': 'Sagittarius', 'Aql': 'Aquila',
  'Cyg': 'Cygnus', 'Cap': 'Capricornus', 'Aqr': 'Aquarius', 'Peg': 'Pegasus',
  'Tri': 'Triangulum', 'Crv': 'Corvus', 'Com': 'Coma Berenices',
  'Ser': 'Serpens', 'Sge': 'Sagitta', 'Del': 'Delphinus',
};

const MAG_LIMIT = 6.5;
const stars = [];

for (let i = 1; i < lines.length; i++) {
  const line = lines[i].trim();
  if (!line) continue;
  const f = parseRow(line);

  const mag = parseFloat(f[idx.mag]);
  if (isNaN(mag) || mag > MAG_LIMIT || mag < -2) continue;  // exclude Sun etc.

  const ra = parseFloat(f[idx.ra]);    // hours
  const dec = parseFloat(f[idx.dec]);  // degrees
  if (isNaN(ra) || isNaN(dec)) continue;

  const proper = f[idx.proper]?.trim() || null;
  const con = f[idx.con]?.trim() || null;

  stars.push([
    Math.round(ra * 10000) / 10000,     // RA hours, 4 decimal places
    Math.round(dec * 1000) / 1000,       // Dec degrees, 3 decimal places
    Math.round(mag * 100) / 100,         // mag, 2 decimal places
    con || null,                          // constellation abbreviation
    proper || null                        // proper name (null if none)
  ]);
}

// Sort by magnitude (brightest first)
stars.sort((a, b) => a[2] - b[2]);

// Split into tiers for stats
const tier1 = stars.filter(s => s[2] <= 4.5);
const tier2 = stars.filter(s => s[2] > 4.5);

console.log(`Total naked-eye stars (mag ≤ ${MAG_LIMIT}): ${stars.length}`);
console.log(`Tier 1 (mag ≤ 4.5): ${tier1.length}`);
console.log(`Tier 2 (mag 4.5–6.5): ${tier2.length}`);
console.log(`Named stars: ${stars.filter(s => s[4]).length}`);

// Count unique constellations
const conSet = new Set(stars.map(s => s[3]).filter(Boolean));
console.log(`Constellations represented: ${conSet.size}`);

// Check which of our display constellations are covered
const ourCons = Object.values(CON_MAP);
const coveredCons = new Set(stars.map(s => CON_MAP[s[3]]).filter(Boolean));
const missing = ourCons.filter(c => !coveredCons.has(c));
if (missing.length) console.log('Missing constellation coverage:', missing);

// Write JS file
const conMapStr = JSON.stringify(CON_MAP);
const output = `// HYG v4.1 star catalog — naked-eye stars (mag ≤ ${MAG_LIMIT})
// Auto-generated by build-stars.js from astronexus/HYG-Database (CC BY-SA 4.0)
// Each entry: [RA_hours, Dec_deg, mag, constellation_abbrev, proper_name]
// Sorted by magnitude (brightest first). ${stars.length} stars total.
// Tier 1 (mag ≤ 4.5): ${tier1.length} stars — always visible
// Tier 2 (mag 4.5–6.5): ${tier2.length} stars — revealed on zoom

const STAR_CATALOG = ${JSON.stringify(stars)};

// Map HYG constellation abbreviations to display names
const CON_ABBREV_TO_NAME = ${conMapStr};
`;

fs.writeFileSync('stars.js', output);
const sizeKB = (Buffer.byteLength(output) / 1024).toFixed(0);
console.log(`Written stars.js (${sizeKB} KB)`);
