// ═══ Fairy Calendar — cities.js ═══
const CITIES = [
  // [name, lat, lon, tz, region, country]
  ['Pago Pago',           -14.3, -170.7, 'Pacific/Pago_Pago',              '',    'American Samoa'],
  ['Honolulu',             21.3, -157.8, 'Pacific/Honolulu',               'HI',  'USA'],
  ['Anchorage',            61.2, -149.9, 'America/Anchorage',              'AK',  'USA'],
  ['Vancouver',            49.2, -123.1, 'America/Vancouver',              'BC',  'Canada'],
  ['Seattle',              47.6, -122.3, 'America/Los_Angeles',            'WA',  'USA'],
  ['Portland',             45.5, -122.7, 'America/Los_Angeles',            'OR',  'USA'],
  ['San Francisco',        37.8, -122.4, 'America/Los_Angeles',            'CA',  'USA'],
  ['Los Angeles',          34.1, -118.2, 'America/Los_Angeles',            'CA',  'USA'],
  ['San Diego',            32.7, -117.2, 'America/Los_Angeles',            'CA',  'USA'],
  ['Las Vegas',            36.2, -115.1, 'America/Los_Angeles',            'NV',  'USA'],
  ['Salt Lake City',       40.8, -111.9, 'America/Denver',                 'UT',  'USA'],
  ['Phoenix',              33.4, -112.1, 'America/Phoenix',                'AZ',  'USA'],
  ['Albuquerque',          35.1, -106.7, 'America/Denver',                 'NM',  'USA'],
  ['Denver',               39.7, -104.9, 'America/Denver',                 'CO',  'USA'],
  ['El Paso',              31.8, -106.5, 'America/Denver',                 'TX',  'USA'],
  ['Calgary',              51.0, -114.1, 'America/Edmonton',               'AB',  'Canada'],
  ['Edmonton',             53.5, -113.5, 'America/Edmonton',               'AB',  'Canada'],
  ['Winnipeg',             49.9,  -97.1, 'America/Winnipeg',               'MB',  'Canada'],
  ['Dallas',               32.8,  -96.8, 'America/Chicago',                'TX',  'USA'],
  ['San Antonio',          29.4,  -98.5, 'America/Chicago',                'TX',  'USA'],
  ['Houston',              29.8,  -95.4, 'America/Chicago',                'TX',  'USA'],
  ['Oklahoma City',        35.5,  -97.5, 'America/Chicago',                'OK',  'USA'],
  ['Kansas City',          39.1,  -94.6, 'America/Chicago',                'MO',  'USA'],
  ['Minneapolis',          44.9,  -93.3, 'America/Chicago',                'MN',  'USA'],
  ['New Orleans',          30.0,  -90.1, 'America/Chicago',                'LA',  'USA'],
  ['Memphis',              35.1,  -90.0, 'America/Chicago',                'TN',  'USA'],
  ['St. Louis',            38.6,  -90.2, 'America/Chicago',                'MO',  'USA'],
  ['Mexico City',          19.4,  -99.1, 'America/Mexico_City',            '',    'Mexico'],
  ['Milwaukee',            43.0,  -87.9, 'America/Chicago',                'WI',  'USA'],
  ['Chicago',              41.8,  -87.6, 'America/Chicago',                'IL',  'USA'],
  ['Nashville',            36.2,  -86.8, 'America/Chicago',                'TN',  'USA'],
  ['Indianapolis',         39.8,  -86.2, 'America/Indiana/Indianapolis',   'IN',  'USA'],
  ['Guatemala City',       14.6,  -90.5, 'America/Guatemala',              '',    'Guatemala'],
  ['Detroit',              42.3,  -83.0, 'America/Detroit',                'MI',  'USA'],
  ['Columbus',             40.0,  -82.9, 'America/New_York',               'OH',  'USA'],
  ['Atlanta',              33.7,  -84.4, 'America/New_York',               'GA',  'USA'],
  ['Cleveland',            41.5,  -81.7, 'America/New_York',               'OH',  'USA'],
  ['Pittsburgh',           40.4,  -80.0, 'America/New_York',               'PA',  'USA'],
  ['Charlotte',            35.2,  -80.8, 'America/New_York',               'NC',  'USA'],
  ['Toronto',              43.7,  -79.4, 'America/Toronto',                'ON',  'Canada'],
  ['Montreal',             45.5,  -73.6, 'America/Toronto',                'QC',  'Canada'],
  ['Washington DC',        38.9,  -77.0, 'America/New_York',               'DC',  'USA'],
  ['Richmond',             37.5,  -77.5, 'America/New_York',               'VA',  'USA'],
  ['Jacksonville',         30.3,  -81.7, 'America/New_York',               'FL',  'USA'],
  ['Philadelphia',         40.0,  -75.2, 'America/New_York',               'PA',  'USA'],
  ['New York',             40.7,  -74.0, 'America/New_York',               'NY',  'USA'],
  ['Orlando',              28.5,  -81.4, 'America/New_York',               'FL',  'USA'],
  ['Miami',                25.8,  -80.2, 'America/New_York',               'FL',  'USA'],
  ['Boston',               42.4,  -71.1, 'America/New_York',               'MA',  'USA'],
  ['Bogotá',                4.7,  -74.1, 'America/Bogota',                 '',    'Colombia'],
  ['Lima',                -12.0,  -77.0, 'America/Lima',                   '',    'Peru'],
  ['Halifax',              44.6,  -63.6, 'America/Halifax',                'NS',  'Canada'],
  ['Caracas',              10.5,  -66.9, 'America/Caracas',                '',    'Venezuela'],
  ['La Paz',              -16.5,  -68.1, 'America/La_Paz',                 '',    'Bolivia'],
  ['Manaus',               -3.1,  -60.0, 'America/Manaus',                 '',    'Brazil'],
  ['Santiago',            -33.5,  -70.7, 'America/Santiago',               '',    'Chile'],
  ['São Paulo',           -23.5,  -46.6, 'America/Sao_Paulo',              '',    'Brazil'],
  ['Buenos Aires',        -34.6,  -58.4, 'America/Argentina/Buenos_Aires', '',    'Argentina'],
  ['Montevideo',          -34.9,  -56.2, 'America/Montevideo',             '',    'Uruguay'],
  ['Nuuk',                 64.2,  -51.7, 'America/Nuuk',                   '',    'Greenland'],
  ['Fernando de Noronha',  -3.9,  -32.4, 'America/Noronha',               '',    'Brazil'],
  ['Praia',                14.9,  -23.5, 'Atlantic/Cape_Verde',            '',    'Cape Verde'],
  ['Reykjavik',            64.1,  -21.9, 'Atlantic/Reykjavik',             '',    'Iceland'],
  ['London',               51.5,   -0.1, 'Europe/London',                  '',    'UK'],
  ['Dublin',               53.3,   -6.3, 'Europe/Dublin',                  '',    'Ireland'],
  ['Lisbon',               38.7,   -9.1, 'Europe/Lisbon',                  '',    'Portugal'],
  ['Abidjan',               5.3,   -4.0, 'Africa/Abidjan',                 '',    "Côte d'Ivoire"],
  ['Accra',                 5.6,   -0.2, 'Africa/Accra',                   '',    'Ghana'],
  ['Casablanca',           33.6,   -7.6, 'Africa/Casablanca',              '',    'Morocco'],
  ['Algiers',              36.7,    3.1, 'Africa/Algiers',                 '',    'Algeria'],
  ['Lagos',                 6.5,    3.4, 'Africa/Lagos',                   '',    'Nigeria'],
  ['Paris',                48.9,    2.3, 'Europe/Paris',                   '',    'France'],
  ['Madrid',               40.4,   -3.7, 'Europe/Madrid',                  '',    'Spain'],
  ['Berlin',               52.5,   13.4, 'Europe/Berlin',                  '',    'Germany'],
  ['Rome',                 41.9,   12.5, 'Europe/Rome',                    '',    'Italy'],
  ['Amsterdam',            52.4,    4.9, 'Europe/Amsterdam',               '',    'Netherlands'],
  ['Warsaw',               52.2,   21.0, 'Europe/Warsaw',                  '',    'Poland'],
  ['Stockholm',            59.3,   18.1, 'Europe/Stockholm',               '',    'Sweden'],
  ['Cairo',                30.1,   31.2, 'Africa/Cairo',                   '',    'Egypt'],
  ['Athens',               38.0,   23.7, 'Europe/Athens',                  '',    'Greece'],
  ['Helsinki',             60.2,   25.0, 'Europe/Helsinki',                '',    'Finland'],
  ['Kyiv',                 50.5,   30.5, 'Europe/Kyiv',                    '',    'Ukraine'],
  ['Bucharest',            44.4,   26.1, 'Europe/Bucharest',               '',    'Romania'],
  ['Johannesburg',        -26.2,   28.0, 'Africa/Johannesburg',            '',    'South Africa'],
  ['Istanbul',             41.0,   28.9, 'Europe/Istanbul',                '',    'Turkey'],
  ['Nairobi',              -1.3,   36.8, 'Africa/Nairobi',                 '',    'Kenya'],
  ['Riyadh',               24.7,   46.7, 'Asia/Riyadh',                    '',    'Saudi Arabia'],
  ['Doha',                 25.3,   51.5, 'Asia/Qatar',                     '',    'Qatar'],
  ['Moscow',               55.7,   37.6, 'Europe/Moscow',                  '',    'Russia'],
  ['Tehran',               35.7,   51.4, 'Asia/Tehran',                    '',    'Iran'],
  ['Dubai',                25.2,   55.3, 'Asia/Dubai',                     '',    'UAE'],
  ['Tbilisi',              41.7,   44.8, 'Asia/Tbilisi',                   '',    'Georgia'],
  ['Yerevan',              40.2,   44.5, 'Asia/Yerevan',                   '',    'Armenia'],
  ['Baku',                 40.4,   49.9, 'Asia/Baku',                      '',    'Azerbaijan'],
  ['Kabul',                34.5,   69.2, 'Asia/Kabul',                     '',    'Afghanistan'],
  ['Karachi',              24.9,   67.0, 'Asia/Karachi',                   '',    'Pakistan'],
  ['Islamabad',            33.7,   73.1, 'Asia/Karachi',                   '',    'Pakistan'],
  ['Tashkent',             41.3,   69.3, 'Asia/Tashkent',                  '',    'Uzbekistan'],
  ['Mumbai',               19.1,   72.9, 'Asia/Kolkata',                   '',    'India'],
  ['Kolkata',              22.6,   88.4, 'Asia/Kolkata',                   '',    'India'],
  ['Kathmandu',            27.7,   85.3, 'Asia/Kathmandu',                 '',    'Nepal'],
  ['Dhaka',                23.7,   90.4, 'Asia/Dhaka',                     '',    'Bangladesh'],
  ['Almaty',               43.3,   77.0, 'Asia/Almaty',                    '',    'Kazakhstan'],
  ['Bishkek',              42.9,   74.6, 'Asia/Bishkek',                   '',    'Kyrgyzstan'],
  ['Yangon',               16.8,   96.2, 'Asia/Yangon',                    '',    'Myanmar'],
  ['Bangkok',              13.8,  100.5, 'Asia/Bangkok',                   '',    'Thailand'],
  ['Ho Chi Minh City',     10.8,  106.7, 'Asia/Ho_Chi_Minh',               '',    'Vietnam'],
  ['Jakarta',              -6.2,  106.8, 'Asia/Jakarta',                   '',    'Indonesia'],
  ['Kuala Lumpur',          3.1,  101.7, 'Asia/Kuala_Lumpur',              '',    'Malaysia'],
  ['Singapore',             1.4,  103.8, 'Asia/Singapore',                 '',    'Singapore'],
  ['Beijing',              39.9,  116.4, 'Asia/Shanghai',                  '',    'China'],
  ['Shanghai',             31.2,  121.5, 'Asia/Shanghai',                  '',    'China'],
  ['Hong Kong',            22.3,  114.2, 'Asia/Hong_Kong',                 '',    'China'],
  ['Manila',               14.6,  121.0, 'Asia/Manila',                    '',    'Philippines'],
  ['Perth',               -31.9,  115.9, 'Australia/Perth',                'WA',  'Australia'],
  ['Seoul',                37.6,  127.0, 'Asia/Seoul',                     '',    'South Korea'],
  ['Tokyo',                35.7,  139.7, 'Asia/Tokyo',                     '',    'Japan'],
  ['Darwin',              -12.5,  130.8, 'Australia/Darwin',               'NT',  'Australia'],
  ['Adelaide',            -34.9,  138.6, 'Australia/Adelaide',             'SA',  'Australia'],
  ['Brisbane',            -27.5,  153.0, 'Australia/Brisbane',             'QLD', 'Australia'],
  ['Sydney',              -33.9,  151.2, 'Australia/Sydney',               'NSW', 'Australia'],
  ['Melbourne',           -37.8,  145.0, 'Australia/Melbourne',            'VIC', 'Australia'],
  ['Vladivostok',          43.1,  131.9, 'Asia/Vladivostok',               '',    'Russia'],
  ['Port Moresby',         -9.4,  147.2, 'Pacific/Port_Moresby',           '',    'Papua New Guinea'],
  ['Noumea',              -22.3,  166.5, 'Pacific/Noumea',                 '',    'New Caledonia'],
  ['Honiara',              -9.4,  160.0, 'Pacific/Guadalcanal',            '',    'Solomon Islands'],
  ['Auckland',            -36.9,  174.8, 'Pacific/Auckland',               '',    'New Zealand'],
  ['Suva',                -18.1,  178.4, 'Pacific/Fiji',                   '',    'Fiji'],
  ['Apia',                -13.8, -172.0, 'Pacific/Apia',                   '',    'Samoa'],
  ["Nuku'alofa",          -21.1, -175.2, 'Pacific/Tongatapu',              '',    'Tonga'],
];
