// ═══ Fairy Calendar — cities.js ═══
const CITIES = [
  // [name, lat, lon, tz, region, country]

  // ── UTC-11 / UTC-13 ──
  ['Pago Pago',                -14.3, -170.7, 'Pacific/Pago_Pago',              '',    'American Samoa'],
  ['Apia',                     -13.8, -172.0, 'Pacific/Apia',                   '',    'Samoa'],
  ["Nuku'alofa",               -21.1, -175.2, 'Pacific/Tongatapu',              '',    'Tonga'],

  // ── UTC-10 ──
  ['Honolulu',                  21.3, -157.8, 'Pacific/Honolulu',               'HI',  'USA'],

  // ── UTC-9 ──
  ['Anchorage',                 61.2, -149.9, 'America/Anchorage',              'AK',  'USA'],

  // ── UTC-8 ──
  ['Vancouver',                 49.2, -123.1, 'America/Vancouver',              'BC',  'Canada'],
  ['Seattle',                   47.6, -122.3, 'America/Los_Angeles',            'WA',  'USA'],
  ['Portland',                  45.5, -122.7, 'America/Los_Angeles',            'OR',  'USA'],
  ['San Francisco',             37.8, -122.4, 'America/Los_Angeles',            'CA',  'USA'],
  ['Los Angeles',               34.1, -118.2, 'America/Los_Angeles',            'CA',  'USA'],
  ['San Diego',                 32.7, -117.2, 'America/Los_Angeles',            'CA',  'USA'],
  ['Las Vegas',                 36.2, -115.1, 'America/Los_Angeles',            'NV',  'USA'],

  // ── UTC-7 ──
  ['Calgary',                   51.0, -114.1, 'America/Edmonton',               'AB',  'Canada'],
  ['Edmonton',                  53.5, -113.5, 'America/Edmonton',               'AB',  'Canada'],
  ['Salt Lake City',            40.8, -111.9, 'America/Denver',                 'UT',  'USA'],
  ['Phoenix',                   33.4, -112.1, 'America/Phoenix',                'AZ',  'USA'],
  ['Denver',                    39.7, -104.9, 'America/Denver',                 'CO',  'USA'],
  ['Albuquerque',               35.1, -106.7, 'America/Denver',                 'NM',  'USA'],
  ['El Paso',                   31.8, -106.5, 'America/Denver',                 'TX',  'USA'],

  // ── UTC-6 ──
  ['Winnipeg',                  49.9,  -97.1, 'America/Winnipeg',               'MB',  'Canada'],
  ['Mexico City',               19.4,  -99.1, 'America/Mexico_City',            '',    'Mexico'],
  ['Dallas',                    32.8,  -96.8, 'America/Chicago',                'TX',  'USA'],
  ['San Antonio',               29.4,  -98.5, 'America/Chicago',                'TX',  'USA'],
  ['Houston',                   29.8,  -95.4, 'America/Chicago',                'TX',  'USA'],
  ['Oklahoma City',             35.5,  -97.5, 'America/Chicago',                'OK',  'USA'],
  ['Kansas City',               39.1,  -94.6, 'America/Chicago',                'MO',  'USA'],
  ['Minneapolis',               44.9,  -93.3, 'America/Chicago',                'MN',  'USA'],
  ['New Orleans',               30.0,  -90.1, 'America/Chicago',                'LA',  'USA'],
  ['Memphis',                   35.1,  -90.0, 'America/Chicago',                'TN',  'USA'],
  ['St. Louis',                 38.6,  -90.2, 'America/Chicago',                'MO',  'USA'],
  ['Milwaukee',                 43.0,  -87.9, 'America/Chicago',                'WI',  'USA'],
  ['Chicago',                   41.8,  -87.6, 'America/Chicago',                'IL',  'USA'],
  ['Nashville',                 36.2,  -86.8, 'America/Chicago',                'TN',  'USA'],
  ['Indianapolis',              39.8,  -86.2, 'America/Indiana/Indianapolis',   'IN',  'USA'],
  ['Guatemala City',            14.6,  -90.5, 'America/Guatemala',              '',    'Guatemala'],
  ['Belmopan',                  17.3,  -88.8, 'America/Belize',                 '',    'Belize'],
  ['San Salvador',              13.7,  -89.2, 'America/El_Salvador',            '',    'El Salvador'],
  ['Tegucigalpa',               14.1,  -87.2, 'America/Tegucigalpa',            '',    'Honduras'],
  ['Managua',                   12.1,  -86.3, 'America/Managua',                '',    'Nicaragua'],

  // ── UTC-5/6 ──
  ['San José',                  10.0,  -84.1, 'America/Costa_Rica',             '',    'Costa Rica'],

  // ── UTC-5 ──
  ['Havana',                    23.1,  -82.4, 'America/Havana',                 '',    'Cuba'],
  ['Detroit',                   42.3,  -83.0, 'America/Detroit',                'MI',  'USA'],
  ['Columbus',                  40.0,  -82.9, 'America/New_York',               'OH',  'USA'],
  ['Jacksonville',              30.3,  -81.7, 'America/New_York',               'FL',  'USA'],
  ['Atlanta',                   33.7,  -84.4, 'America/New_York',               'GA',  'USA'],
  ['Orlando',                   28.5,  -81.4, 'America/New_York',               'FL',  'USA'],
  ['Cleveland',                 41.5,  -81.7, 'America/New_York',               'OH',  'USA'],
  ['Pittsburgh',                40.4,  -80.0, 'America/New_York',               'PA',  'USA'],
  ['Charlotte',                 35.2,  -80.8, 'America/New_York',               'NC',  'USA'],
  ['Miami',                     25.8,  -80.2, 'America/New_York',               'FL',  'USA'],
  ['Panama City',                9.0,  -79.5, 'America/Panama',                 '',    'Panama'],
  ['Toronto',                   43.7,  -79.4, 'America/Toronto',                'ON',  'Canada'],
  ['Washington DC',             38.9,  -77.0, 'America/New_York',               'DC',  'USA'],
  ['Richmond',                  37.5,  -77.5, 'America/New_York',               'VA',  'USA'],
  ['Nassau',                    25.1,  -77.4, 'America/Nassau',                 '',    'Bahamas'],
  ['Lima',                     -12.0,  -77.0, 'America/Lima',                   '',    'Peru'],
  ['Kingston',                  18.0,  -76.8, 'America/Jamaica',                '',    'Jamaica'],
  ['Philadelphia',              40.0,  -75.2, 'America/New_York',               'PA',  'USA'],
  ['Ottawa',                    45.4,  -75.7, 'America/Toronto',                'ON',  'Canada'],
  ['New York',                  40.7,  -74.0, 'America/New_York',               'NY',  'USA'],
  ['Bogotá',                     4.7,  -74.1, 'America/Bogota',                 '',    'Colombia'],
  ['Quito',                     -0.2,  -78.5, 'America/Guayaquil',              '',    'Ecuador'],
  ['Boston',                    42.4,  -71.1, 'America/New_York',               'MA',  'USA'],
  ['Port-au-Prince',            18.5,  -72.3, 'America/Port-au-Prince',         '',    'Haiti'],
  ['Santo Domingo',             18.5,  -69.9, 'America/Santo_Domingo',          '',    'Dominican Republic'],

  // ── UTC-4 ──
  ['Halifax',                   44.6,  -63.6, 'America/Halifax',                'NS',  'Canada'],
  ['Montreal',                  45.5,  -73.6, 'America/Toronto',                'QC',  'Canada'],
  ['Caracas',                   10.5,  -66.9, 'America/Caracas',                '',    'Venezuela'],
  ['La Paz',                   -16.5,  -68.1, 'America/La_Paz',                 '',    'Bolivia'],
  ['Basseterre',                17.3,  -62.7, 'America/St_Kitts',               '',    'Saint Kitts and Nevis'],
  ["St. John's",                17.1,  -61.8, 'America/Antigua',                '',    'Antigua and Barbuda'],
  ['Roseau',                    15.3,  -61.4, 'America/Dominica',               '',    'Dominica'],
  ['Kingstown',                 13.2,  -61.2, 'America/St_Vincent',             '',    'Saint Vincent and the Grenadines'],
  ['Castries',                  14.0,  -61.0, 'America/St_Lucia',               '',    'Saint Lucia'],
  ["St. George's",              12.1,  -61.7, 'America/Grenada',                '',    'Grenada'],
  ['Port of Spain',             10.7,  -61.5, 'America/Port_of_Spain',          '',    'Trinidad and Tobago'],
  ['Bridgetown',                13.1,  -59.6, 'America/Barbados',               '',    'Barbados'],
  ['Georgetown',                 6.8,  -58.2, 'America/Guyana',                 '',    'Guyana'],

  // ── UTC-3 ──
  ['Paramaribo',                 5.8,  -55.2, 'America/Paramaribo',             '',    'Suriname'],
  ['Manaus',                    -3.1,  -60.0, 'America/Manaus',                 '',    'Brazil'],
  ['Santiago',                 -33.5,  -70.7, 'America/Santiago',               '',    'Chile'],
  ['Asunción',                 -25.3,  -57.6, 'America/Asuncion',               '',    'Paraguay'],
  ['Buenos Aires',             -34.6,  -58.4, 'America/Argentina/Buenos_Aires', '',    'Argentina'],
  ['Montevideo',               -34.9,  -56.2, 'America/Montevideo',             '',    'Uruguay'],
  ['Brasília',                 -15.8,  -47.9, 'America/Sao_Paulo',              '',    'Brazil'],
  ['São Paulo',                -23.5,  -46.6, 'America/Sao_Paulo',              '',    'Brazil'],

  // ── UTC-2 ──
  ['Nuuk',                      64.2,  -51.7, 'America/Nuuk',                   '',    'Greenland'],
  ['Fernando de Noronha',       -3.9,  -32.4, 'America/Noronha',               '',    'Brazil'],

  // ── UTC-1 ──
  ['Praia',                     14.9,  -23.5, 'Atlantic/Cape_Verde',            '',    'Cape Verde'],

  // ── UTC+0 ──
  ['Reykjavik',                 64.1,  -21.9, 'Atlantic/Reykjavik',             '',    'Iceland'],
  ['London',                    51.5,   -0.1, 'Europe/London',                  '',    'UK'],
  ['Dublin',                    53.3,   -6.3, 'Europe/Dublin',                  '',    'Ireland'],
  ['Lisbon',                    38.7,   -9.1, 'Europe/Lisbon',                  '',    'Portugal'],
  ['Nouakchott',                18.1,  -15.9, 'Africa/Nouakchott',              '',    'Mauritania'],
  ['Dakar',                     14.7,  -17.4, 'Africa/Dakar',                   '',    'Senegal'],
  ['Banjul',                    13.5,  -16.6, 'Africa/Banjul',                  '',    'Gambia'],
  ['Bissau',                    11.9,  -15.6, 'Africa/Bissau',                  '',    'Guinea-Bissau'],
  ['Conakry',                    9.5,  -13.7, 'Africa/Conakry',                 '',    'Guinea'],
  ['Freetown',                   8.5,  -13.2, 'Africa/Freetown',                '',    'Sierra Leone'],
  ['Monrovia',                   6.3,  -10.8, 'Africa/Monrovia',                '',    'Liberia'],
  ['Bamako',                    12.7,   -8.0, 'Africa/Bamako',                  '',    'Mali'],
  ['Casablanca',                33.6,   -7.6, 'Africa/Casablanca',              '',    'Morocco'],
  ['Rabat',                     34.0,   -6.8, 'Africa/Casablanca',              '',    'Morocco'],
  ['Madrid',                    40.4,   -3.7, 'Europe/Madrid',                  '',    'Spain'],
  ['Abidjan',                    5.3,   -4.0, 'Africa/Abidjan',                 '',    "Côte d'Ivoire"],
  ['Yamoussoukro',               6.8,   -5.3, 'Africa/Abidjan',                 '',    "Côte d'Ivoire"],
  ['Accra',                      5.6,   -0.2, 'Africa/Accra',                   '',    'Ghana'],

  // ── UTC+1 ──
  ['Paris',                     48.9,    2.3, 'Europe/Paris',                   '',    'France'],
  ['Andorra la Vella',          42.5,    1.5, 'Europe/Andorra',                 '',    'Andorra'],
  ['Amsterdam',                 52.4,    4.9, 'Europe/Amsterdam',               '',    'Netherlands'],
  ['Brussels',                  50.8,    4.4, 'Europe/Brussels',                '',    'Belgium'],
  ['Luxembourg City',           49.6,    6.1, 'Europe/Luxembourg',              '',    'Luxembourg'],
  ['Bern',                      46.9,    7.4, 'Europe/Zurich',                  '',    'Switzerland'],
  ['Monaco',                    43.7,    7.4, 'Europe/Monaco',                  '',    'Monaco'],
  ['Oslo',                      59.9,   10.7, 'Europe/Oslo',                    '',    'Norway'],
  ['Copenhagen',                55.7,   12.6, 'Europe/Copenhagen',              '',    'Denmark'],
  ['Algiers',                   36.7,    3.1, 'Africa/Algiers',                 '',    'Algeria'],
  ['Tunis',                     36.8,   10.2, 'Africa/Tunis',                   '',    'Tunisia'],
  ['Ouagadougou',               12.4,   -1.5, 'Africa/Ouagadougou',             '',    'Burkina Faso'],
  ['Niamey',                    13.5,    2.1, 'Africa/Niamey',                  '',    'Niger'],
  ['Lomé',                       6.1,    1.2, 'Africa/Lome',                    '',    'Togo'],
  ['Porto-Novo',                 6.5,    2.6, 'Africa/Porto-Novo',              '',    'Benin'],
  ['Lagos',                      6.5,    3.4, 'Africa/Lagos',                   '',    'Nigeria'],
  ['Abuja',                      9.1,    7.5, 'Africa/Lagos',                   '',    'Nigeria'],
  ['São Tomé',                   0.3,    6.7, 'Africa/Sao_Tome',                '',    'São Tomé and Príncipe'],
  ['Malabo',                     3.8,    8.8, 'Africa/Malabo',                  '',    'Equatorial Guinea'],
  ['Yaoundé',                    3.9,   11.5, 'Africa/Douala',                  '',    'Cameroon'],
  ['Libreville',                 0.4,    9.4, 'Africa/Libreville',              '',    'Gabon'],
  ["N'Djamena",                 12.1,   15.1, 'Africa/Ndjamena',                '',    'Chad'],
  ['Bangui',                     4.4,   18.6, 'Africa/Bangui',                  '',    'Central African Republic'],
  ['Brazzaville',               -4.3,   15.3, 'Africa/Brazzaville',             '',    'Republic of the Congo'],
  ['Kinshasa',                  -4.3,   15.3, 'Africa/Kinshasa',                '',    'DR Congo'],
  ['Luanda',                    -8.8,   13.2, 'Africa/Luanda',                  '',    'Angola'],
  ['Tripoli',                   32.9,   13.2, 'Africa/Tripoli',                 '',    'Libya'],

  // ── UTC+2 ──
  ['Berlin',                    52.5,   13.4, 'Europe/Berlin',                  '',    'Germany'],
  ['Rome',                      41.9,   12.5, 'Europe/Rome',                    '',    'Italy'],
  ['Vatican City',              41.9,   12.5, 'Europe/Vatican',                 '',    'Vatican'],
  ['San Marino',                43.9,   12.4, 'Europe/San_Marino',              '',    'San Marino'],
  ['Valletta',                  35.9,   14.5, 'Europe/Malta',                   '',    'Malta'],
  ['Vienna',                    48.2,   16.4, 'Europe/Vienna',                  '',    'Austria'],
  ['Vaduz',                     47.1,    9.5, 'Europe/Vaduz',                   '',    'Liechtenstein'],
  ['Prague',                    50.1,   14.4, 'Europe/Prague',                  '',    'Czechia'],
  ['Bratislava',                48.1,   17.1, 'Europe/Bratislava',              '',    'Slovakia'],
  ['Budapest',                  47.5,   19.1, 'Europe/Budapest',                '',    'Hungary'],
  ['Ljubljana',                 46.1,   14.5, 'Europe/Ljubljana',               '',    'Slovenia'],
  ['Zagreb',                    45.8,   16.0, 'Europe/Zagreb',                  '',    'Croatia'],
  ['Sarajevo',                  43.8,   18.4, 'Europe/Sarajevo',                '',    'Bosnia and Herzegovina'],
  ['Warsaw',                    52.2,   21.0, 'Europe/Warsaw',                  '',    'Poland'],
  ['Stockholm',                 59.3,   18.1, 'Europe/Stockholm',               '',    'Sweden'],
  ['Belgrade',                  44.8,   20.5, 'Europe/Belgrade',                '',    'Serbia'],
  ['Podgorica',                 42.4,   19.3, 'Europe/Podgorica',               '',    'Montenegro'],
  ['Pristina',                  42.7,   21.2, 'Europe/Skopje',                  '',    'Kosovo'],
  ['Skopje',                    42.0,   21.4, 'Europe/Skopje',                  '',    'North Macedonia'],
  ['Tirana',                    41.3,   19.8, 'Europe/Tirane',                  '',    'Albania'],
  ['Sofia',                     42.7,   23.3, 'Europe/Sofia',                   '',    'Bulgaria'],
  ['Athens',                    38.0,   23.7, 'Europe/Athens',                  '',    'Greece'],
  ['Tallinn',                   59.4,   24.8, 'Europe/Tallinn',                 '',    'Estonia'],
  ['Riga',                      56.9,   24.1, 'Europe/Riga',                    '',    'Latvia'],
  ['Vilnius',                   54.7,   25.3, 'Europe/Vilnius',                 '',    'Lithuania'],
  ['Helsinki',                  60.2,   25.0, 'Europe/Helsinki',                '',    'Finland'],
  ['Minsk',                     53.9,   27.6, 'Europe/Minsk',                   '',    'Belarus'],
  ['Kyiv',                      50.5,   30.5, 'Europe/Kyiv',                    '',    'Ukraine'],
  ['Chisinau',                  47.0,   28.9, 'Europe/Chisinau',                '',    'Moldova'],
  ['Bucharest',                 44.4,   26.1, 'Europe/Bucharest',               '',    'Romania'],
  ['Cairo',                     30.1,   31.2, 'Africa/Cairo',                   '',    'Egypt'],
  ['Johannesburg',             -26.2,   28.0, 'Africa/Johannesburg',            '',    'South Africa'],
  ['Pretoria',                 -25.7,   28.2, 'Africa/Johannesburg',            '',    'South Africa'],
  ['Windhoek',                 -22.6,   17.1, 'Africa/Windhoek',                '',    'Namibia'],
  ['Gaborone',                 -24.7,   25.9, 'Africa/Gaborone',                '',    'Botswana'],
  ['Maseru',                   -29.3,   27.5, 'Africa/Maseru',                  '',    'Lesotho'],
  ['Mbabane',                  -26.3,   31.1, 'Africa/Mbabane',                 '',    'Eswatini'],
  ['Lusaka',                   -15.4,   28.3, 'Africa/Lusaka',                  '',    'Zambia'],
  ['Harare',                   -17.8,   31.1, 'Africa/Harare',                  '',    'Zimbabwe'],
  ['Kigali',                    -1.9,   30.1, 'Africa/Kigali',                  '',    'Rwanda'],
  ['Gitega',                    -3.4,   29.9, 'Africa/Bujumbura',               '',    'Burundi'],
  ['Kampala',                    0.3,   32.6, 'Africa/Kampala',                 '',    'Uganda'],
  ['Juba',                       4.9,   31.6, 'Africa/Juba',                    '',    'South Sudan'],
  ['Khartoum',                  15.6,   32.5, 'Africa/Khartoum',                '',    'Sudan'],
  ['Istanbul',                  41.0,   28.9, 'Europe/Istanbul',                '',    'Turkey'],
  ['Ankara',                    39.9,   32.9, 'Europe/Istanbul',                '',    'Turkey'],
  ['Nicosia',                   35.2,   33.4, 'Asia/Nicosia',                   '',    'Cyprus'],

  // ── UTC+3 ──
  ['Moscow',                    55.7,   37.6, 'Europe/Moscow',                  '',    'Russia'],
  ['Nairobi',                   -1.3,   36.8, 'Africa/Nairobi',                 '',    'Kenya'],
  ['Dodoma',                    -6.2,   35.7, 'Africa/Dar_es_Salaam',           '',    'Tanzania'],
  ['Lilongwe',                 -14.0,   33.8, 'Africa/Blantyre',                '',    'Malawi'],
  ['Maputo',                   -25.9,   32.6, 'Africa/Maputo',                  '',    'Mozambique'],
  ['Amman',                     31.9,   35.9, 'Asia/Amman',                     '',    'Jordan'],
  ['Jerusalem',                 31.8,   35.2, 'Asia/Jerusalem',                 '',    'Israel'],
  ['Beirut',                    33.9,   35.5, 'Asia/Beirut',                    '',    'Lebanon'],
  ['Damascus',                  33.5,   36.3, 'Asia/Damascus',                  '',    'Syria'],
  ['Asmara',                    15.3,   38.9, 'Africa/Asmara',                  '',    'Eritrea'],
  ['Addis Ababa',                9.0,   38.7, 'Africa/Addis_Ababa',             '',    'Ethiopia'],
  ['Djibouti',                  11.6,   43.1, 'Africa/Djibouti',                '',    'Djibouti'],
  ['Mogadishu',                  2.0,   45.3, 'Africa/Mogadishu',               '',    'Somalia'],
  ['Baghdad',                   33.3,   44.4, 'Asia/Baghdad',                   '',    'Iraq'],
  ['Kuwait City',               29.4,   48.0, 'Asia/Kuwait',                    '',    'Kuwait'],
  ['Riyadh',                    24.7,   46.7, 'Asia/Riyadh',                    '',    'Saudi Arabia'],
  ["Sana'a",                    15.4,   44.2, 'Asia/Aden',                      '',    'Yemen'],
  ['Tbilisi',                   41.7,   44.8, 'Asia/Tbilisi',                   '',    'Georgia'],
  ['Yerevan',                   40.2,   44.5, 'Asia/Yerevan',                   '',    'Armenia'],
  ['Moroni',                   -11.7,   43.3, 'Indian/Comoro',                  '',    'Comoros'],
  ['Antananarivo',             -18.9,   47.5, 'Indian/Antananarivo',            '',    'Madagascar'],

  // ── UTC+3.5 / UTC+4 ──
  ['Tehran',                    35.7,   51.4, 'Asia/Tehran',                    '',    'Iran'],
  ['Doha',                      25.3,   51.5, 'Asia/Qatar',                     '',    'Qatar'],
  ['Manama',                    26.2,   50.6, 'Asia/Bahrain',                   '',    'Bahrain'],
  ['Baku',                      40.4,   49.9, 'Asia/Baku',                      '',    'Azerbaijan'],
  ['Abu Dhabi',                 24.5,   54.4, 'Asia/Dubai',                     '',    'UAE'],
  ['Dubai',                     25.2,   55.3, 'Asia/Dubai',                     '',    'UAE'],
  ['Victoria',                  -4.6,   55.5, 'Indian/Mahe',                    '',    'Seychelles'],
  ['Port Louis',               -20.2,   57.5, 'Indian/Mauritius',               '',    'Mauritius'],

  // ── UTC+4 / UTC+5 ──
  ['Muscat',                    23.6,   58.6, 'Asia/Muscat',                    '',    'Oman'],
  ['Ashgabat',                  37.9,   58.4, 'Asia/Ashgabat',                  '',    'Turkmenistan'],
  ['Kabul',                     34.5,   69.2, 'Asia/Kabul',                     '',    'Afghanistan'],
  ['Karachi',                   24.9,   67.0, 'Asia/Karachi',                   '',    'Pakistan'],
  ['Islamabad',                 33.7,   73.1, 'Asia/Karachi',                   '',    'Pakistan'],
  ['Dushanbe',                  38.5,   68.8, 'Asia/Dushanbe',                  '',    'Tajikistan'],
  ['Tashkent',                  41.3,   69.3, 'Asia/Tashkent',                  '',    'Uzbekistan'],
  ['Astana',                    51.2,   71.5, 'Asia/Almaty',                    '',    'Kazakhstan'],
  ['Almaty',                    43.3,   77.0, 'Asia/Almaty',                    '',    'Kazakhstan'],

  // ── UTC+5.5 / UTC+6 ──
  ['New Delhi',                 28.6,   77.2, 'Asia/Kolkata',                   '',    'India'],
  ['Mumbai',                    19.1,   72.9, 'Asia/Kolkata',                   '',    'India'],
  ['Malé',                       4.2,   73.5, 'Indian/Maldives',                '',    'Maldives'],
  ['Colombo',                    6.9,   79.9, 'Asia/Colombo',                   '',    'Sri Lanka'],
  ['Bishkek',                   42.9,   74.6, 'Asia/Bishkek',                   '',    'Kyrgyzstan'],
  ['Kolkata',                   22.6,   88.4, 'Asia/Kolkata',                   '',    'India'],
  ['Kathmandu',                 27.7,   85.3, 'Asia/Kathmandu',                 '',    'Nepal'],
  ['Thimphu',                   27.5,   89.6, 'Asia/Thimphu',                   '',    'Bhutan'],
  ['Dhaka',                     23.7,   90.4, 'Asia/Dhaka',                     '',    'Bangladesh'],

  // ── UTC+6.5 / UTC+7 ──
  ['Yangon',                    16.8,   96.2, 'Asia/Yangon',                    '',    'Myanmar'],
  ['Naypyidaw',                 19.8,   96.1, 'Asia/Yangon',                    '',    'Myanmar'],
  ['Bangkok',                   13.8,  100.5, 'Asia/Bangkok',                   '',    'Thailand'],
  ['Vientiane',                 17.9,  102.6, 'Asia/Vientiane',                 '',    'Laos'],
  ['Phnom Penh',                11.6,  104.9, 'Asia/Phnom_Penh',                '',    'Cambodia'],
  ['Hanoi',                     21.0,  105.8, 'Asia/Ho_Chi_Minh',               '',    'Vietnam'],
  ['Ho Chi Minh City',          10.8,  106.7, 'Asia/Ho_Chi_Minh',               '',    'Vietnam'],
  ['Kuala Lumpur',               3.1,  101.7, 'Asia/Kuala_Lumpur',              '',    'Malaysia'],
  ['Jakarta',                   -6.2,  106.8, 'Asia/Jakarta',                   '',    'Indonesia'],
  ['Singapore',                  1.4,  103.8, 'Asia/Singapore',                 '',    'Singapore'],
  ['Ulaanbaatar',               47.9,  106.9, 'Asia/Ulaanbaatar',               '',    'Mongolia'],

  // ── UTC+8 ──
  ['Beijing',                   39.9,  116.4, 'Asia/Shanghai',                  '',    'China'],
  ['Shanghai',                  31.2,  121.5, 'Asia/Shanghai',                  '',    'China'],
  ['Hong Kong',                 22.3,  114.2, 'Asia/Hong_Kong',                 '',    'China'],
  ['Taipei',                    25.0,  121.5, 'Asia/Taipei',                    '',    'Taiwan'],
  ['Manila',                    14.6,  121.0, 'Asia/Manila',                    '',    'Philippines'],
  ['Bandar Seri Begawan',        4.9,  115.0, 'Asia/Brunei',                    '',    'Brunei'],
  ['Perth',                    -31.9,  115.9, 'Australia/Perth',                'WA',  'Australia'],
  ['Ngerulmud',                  7.5,  134.6, 'Pacific/Palau',                  '',    'Palau'],

  // ── UTC+9 ──
  ['Seoul',                     37.6,  127.0, 'Asia/Seoul',                     '',    'South Korea'],
  ['Pyongyang',                 39.0,  125.8, 'Asia/Pyongyang',                 '',    'North Korea'],
  ['Dili',                      -8.6,  125.6, 'Asia/Dili',                      '',    'Timor-Leste'],
  ['Tokyo',                     35.7,  139.7, 'Asia/Tokyo',                     '',    'Japan'],
  ['Darwin',                   -12.5,  130.8, 'Australia/Darwin',               'NT',  'Australia'],
  ['Vladivostok',               43.1,  131.9, 'Asia/Vladivostok',               '',    'Russia'],

  // ── UTC+9.5 / UTC+10 ──
  ['Adelaide',                 -34.9,  138.6, 'Australia/Adelaide',             'SA',  'Australia'],
  ['Canberra',                 -35.3,  149.1, 'Australia/Sydney',               'ACT', 'Australia'],
  ['Brisbane',                 -27.5,  153.0, 'Australia/Brisbane',             'QLD', 'Australia'],
  ['Sydney',                   -33.9,  151.2, 'Australia/Sydney',               'NSW', 'Australia'],
  ['Melbourne',                -37.8,  145.0, 'Australia/Melbourne',            'VIC', 'Australia'],
  ['Port Moresby',              -9.4,  147.2, 'Pacific/Port_Moresby',           '',    'Papua New Guinea'],
  ['Palikir',                    6.9,  158.2, 'Pacific/Pohnpei',                '',    'Micronesia'],

  // ── UTC+11 ──
  ['Honiara',                   -9.4,  160.0, 'Pacific/Guadalcanal',            '',    'Solomon Islands'],
  ['Noumea',                   -22.3,  166.5, 'Pacific/Noumea',                 '',    'New Caledonia'],
  ['Yaren',                     -0.5,  166.9, 'Pacific/Nauru',                  '',    'Nauru'],
  ['Port Vila',                -17.7,  168.3, 'Pacific/Efate',                  '',    'Vanuatu'],

  // ── UTC+12 ──
  ['Majuro',                     7.1,  171.4, 'Pacific/Majuro',                 '',    'Marshall Islands'],
  ['Tarawa',                     1.3,  173.0, 'Pacific/Tarawa',                 '',    'Kiribati'],
  ['Funafuti',                  -8.5,  179.2, 'Pacific/Funafuti',               '',    'Tuvalu'],
  ['Suva',                     -18.1,  178.4, 'Pacific/Fiji',                   '',    'Fiji'],
  ['Auckland',                 -36.9,  174.8, 'Pacific/Auckland',               '',    'New Zealand'],
  ['Wellington',               -41.3,  174.8, 'Pacific/Auckland',               '',    'New Zealand'],
];
